package com.chrisblackwood.home.dto;

public enum WindowDecision {
    OPEN_FIVE_MINUTES_THEN_CLOSE,
    OPEN_TEN_MINUTES_THEN_CLOSE,
    OPEN_TEN_TO_FIFTEEN_MINUTES_THEN_CRACK_ONE_CM,
    CRACK_ONE_TO_THREE_CM_OVERNIGHT,
    OPEN_OVERNIGHT,
    OPEN_WIDE_OVERNIGHT,
    KEEP_CLOSED
}
